#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Nath
#
# This file is a part of < https://github.com/nathxe/PyroNath-Userbot/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/nathxe/PyroNath-Userbot/blob/main/LICENSE/>.
#
# t.me/nathsupport & t.me/nathaellxx

# start
python3 -m WhyzuProject
