#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Whyzu
#
# This file is a part of < https://github.com/itsmewhy/Whyzu-Userbot/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/itsmewhy/Whyzu-Userbot/blob/main/LICENSE/>.
#
# t.me/WhyzuNotSupport & t.me/WhyzuCH

# start
python3 -m WhyzuProject
